### ISSUE TITLE
Any way to do cross validate?

### ISSUE THREAD

**Issue by w32zhong** [rmit-ir/polyfuse#3]
If not, are we planning to add k-fold cross-validation? like being able to specify a `--k` option to generate validated results?

**Comment by JMMackenzie** [comment]
What would the use-case of cross-validation be here? For setting parameter values?

I suspect you would be better served by simply generating splits and scripting this yourself; it's not a problem specific to polyfuse. That said, perhaps if there is a compelling use-case, someone might be able to help :-)

**Comment by w32zhong** [comment]
Thanks for your comments!
